### PR TITLE
Add dot to patternProperties

### PR DESCRIPTION
**Pull request by mihailpw**
Can not validate data-types/vehicle-type-counts
Probably `.` is missed in patternProperties
Demo https://programiz.pro/ide/python/MZLWCVP8W9

### CODE REVIEW

**Comment by mihailpw** [comment]
PTAL @schnuerle @thekaveman

**Comment by schnuerle** [comment]
Yes it seems to me that 

`patternProperties:
  ".":` 

would be correct.

**Comment by mihailpw** [comment]
PTAL @schnuerle @thekaveman
Please merge or close the PR. Thanks

**Comment by schnuerle** [comment]
Merged thank you!

**Pull request merged**
